name: Tests

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: >
          pip install ruff pytest homeassistant cryptography bleak-retry-connector
          bluetooth-adapters bluetooth-auto-recovery bluetooth-data-tools dbus-fast
          habluetooth aiousbwatcher pyserial
      - name: Lint
        run: ruff check .
      - name: Test
        run: pytest
